package com.keen.erp.entity;

public enum StockMovementType {
    SUPPLIER_RECEIVED,
    WAREHOUSE_TO_SHOP_TRANSFER,
    SHOP_SALE,
    CUSTOMER_RETURN,
    SUPPLIER_RETURN,
    DAMAGED_STOCK,
    LOST_STOCK,
    THEFT_ADJUSTMENT,
    MANUAL_CORRECTION,
    STOCK_COUNT_ADJUSTMENT,
    TRANSFER_IN_TRANSIT,
    TRANSFER_RECEIVED,
    TRANSFER_REJECTED,
    INITIAL_ADJUSTMENT
}
